export const recentSales = [
  {
    id: 0,
    name: "Bamboo Watch",
    category: "Accessories",
    price: "65.00",
    status: "INSTOCK",
  },
  {
    id: 1,
    name: "Black Watch",
    category: "Accessories",
    price: "72.00",
    status: "INSTOCK",
  },
  {
    id: 2,
    name: "Blue Band",
    category: "Fitness",
    price: "79.00",
    status: "LOWSTOCK",
  },
  {
    id: 3,
    name: "Blue T-Shirt",
    category: "Clothing",
    price: "29.00",
    status: "INSTOCK",
  },
  {
    id: 4,
    name: "Bracelet",
    category: "Accessories",
    price: "15.00",
    status: "INSTOCK",
  },
  {
    id: 5,
    name: "Brown Purse",
    category: "Accessories",
    price: "120.00",
    status: "OUTOFSTOCK",
  },
  {
    id: 6,
    name: "Chakra Bracelet",
    category: "Accessories",
    price: "32.00",
    status: "LOWSTOCK",
  },
  {
    id: 7,
    name: "Galaxy Earrings",
    category: "Accessories",
    price: "34.00",
    status: "INSTOCK",
  },
  {
    id: 8,
    name: "Game Controller",
    category: "Electronics",
    price: "99.00",
    status: "LOWSTOCK",
  },
  {
    id: 9,
    name: "Gaming Set",
    category: "Electronics",
    price: "299.00",
    status: "INSTOCK",
  },
];
